# seraphim-config.cmake - package configuration file

get_filename_component(SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(SERAPHIM_INCLUDE_DIRS "@CONF_INCLUDE_DIRS@")

# the core module is always present
set(SERAPHIM_LIBRARIES core)
include(${SELF_DIR}/core.cmake)

if (EXISTS ${SELF_DIR}/iop.cmake)
    set(SERAPHIM_LIBRARIES ${SERAPHIM_LIBRARIES} iop)
    include(${SELF_DIR}/iop.cmake)
endif ()
if (EXISTS ${SELF_DIR}/ipc.cmake)
    set(SERAPHIM_LIBRARIES ${SERAPHIM_LIBRARIES} ipc)
    include(${SELF_DIR}/ipc.cmake)
endif ()
if (EXISTS ${SELF_DIR}/gui.cmake)
    set(SERAPHIM_LIBRARIES ${SERAPHIM_LIBRARIES} gui)
    include(${SELF_DIR}/gui.cmake)
endif ()
if (EXISTS ${SELF_DIR}/car.cmake)
    set(SERAPHIM_LIBRARIES ${SERAPHIM_LIBRARIES} car)
    include(${SELF_DIR}/car.cmake)
endif ()
if (EXISTS ${SELF_DIR}/face.cmake)
    set(SERAPHIM_LIBRARIES ${SERAPHIM_LIBRARIES} face)
    include(${SELF_DIR}/face.cmake)
endif ()
if (EXISTS ${SELF_DIR}/object.cmake)
    set(SERAPHIM_LIBRARIES ${SERAPHIM_LIBRARIES} object)
    include(${SELF_DIR}/object.cmake)
endif ()
